# Dinners {-}

## Hot Dish {-}

### Ingredients {-}

* 1 lb of ground beef

* frozen, cut green beans

* 1 can tomato soup

* 1 bag frozen tater tots

* 1/2 large white onion

* Cheese

### Instructions {-}

Dice and carmelize the onion. Then brown the meat (be sure to drain the fat). Season generously with taco seasoning, etc.

Mix the frozen green beans and cooked meat into a cooking dish. Layer cheese, followed by frozen tater tots.

Place in the oven at 350°F for about 15-20 minutes, until the tater tots are nice and crispy. Add cheese on top and place back in the oven until melted. Serve immediately.

### Notes {-}

There are many variations on this dish.

## Sweet Potate and Lentil Dal {-}

### Ingredients {-}

* 1 Sweet Potato

* 1 cup red lentils

* 1-2 T oil (coconut or vegetable)

* 1 onion, diced

* 2 T minced fresh ginger

* 6 cloves garlic, minced

* 1 t cumin seeds (or ground cumin)

* 1 T Garam Masala

* 1 T Cinnamon (optional)

* 1 t salt

* 1 t sugar

* 2 bay leaves

* spicy peppers, to taste

* Other vegetables: chopped carrots, peas

* 3 cups chicken broth

* 1 can diced tomatoes (or fresh tomatoes diced)

* Tempering oil:

    * 1 t cumin seeds
    
    * 1 t fennel seeds
    
    * 1 t paprkia
    
    * 2 T oil (coconut or vegetable)
    
    
### Instructions {-}

* Cube sweet potatoes and roast in oven at 425 F until done, about 20 minutes.  Set aside.

* Sort and rinse lentils

* Heat oil and saute onions over medium high heat for 2 minutes

* Add ginger and saute a few more minutes

* Add garlic and turn heat down to medium

* Add cumin seeds, garam masala, salt, sugar, bay leaves, peppers, cinnamon.  Stir for 1-2 minutes, until spices become fragrant.

* Add lentils with chicken broth and tomatoes.  Bring to boil, cover and turn heat down.  Let simmer for 15 minutes.

* Once lentils are done, add sweet potatoes.

* In another saute pan, heat 2 T oil.  Add cumin, fennel, paprika and stir for 1 minute (until seeds start to pop).

* Serve dal over rice or bread and drizzle with tempering oil.

## Carne Asada Casserole {-}

Thanks to [Dirk Eddelbuettel](https://twitter.com/eddelbuettel) for introducing me to this receipe.

### Ingredients {-}

Steak marinade:

* 1 skirt or flank steak, weighing around 3/4-1 pound
* 1/4 cup olive oil
* 4 cloves garlic, finely minced
* 1/2 cup freshly chopped cilantro
* The juice of one lime
* 2 tablespoons of orange juice
* 1 teaspoon salt

Cilantro lime rice:

* 2 cups long grain rice, cooked
* 1 tablespoon chopped cilantro
* 1 tablespoon lime juice

Misc:

* 1 can refried beans
* 1 red bell pepper
* 1/2 white onion
* 1 1/4 cups of a shredded jack and cheddar blend, divided
* 6 ounces queso fresco
* sour cream
* salsa verde

### Instructions {-}

Begin by preparing and letting the steak marinade for at least 2 hours.

Cook the rice and mix in the cilantro and lime juice. Combine the rice and refried beans together and then spread the mixture evenly across the bottom of the casserole dish.

Prepare the fajitas by slicing the bell pepper and onion into thin pieces, sautee them in a cast iron pan, and add them to the casserole dish.

Next add 4 oz of the queso fresco.

Remove the steak from the marinade and pat it dry with a clean towel. Heat the cast iron pan over high heat until it is as hot as possible. Sear each side of the steak, roughly 5 minutes each side. Because this can produce a lot of smoke, be sure to have good ventilation. An alternative method is to set the cast iron on the top rack in the oven and set to broil.

Once seared, let the steak rest for 5-10 minutes. Cut the steak into bite size peices, slicing against the grain and then with. The interior should still be quite rare.

Add the steak to the casserole dish and then top with shredded cheese and the rest of the queso fresco.

Bake at 375°F for about 15-20 minutes.

Serve with sour cream and salsa verde.
