# Meat {-}

## Chipotle Chicken {-}

### Ingredients {-}

* 4 boneless chicken breasts

* 2 cans (7 oz) of chipotle peppers in adobo sauce

* 1 tbps cumin

* 2 tsp oregano

* 1 tsp honey

* 2 tbsp olive oil

* 2 cloves garlic

### Instructions {-}

Combine marinade ingredients in a food processor and blend until it has a consistent texture.

Place chicken breasts in a gallon size Ziploc bag and pour in the marinade. Carefully work the marinade around the chicken breasts so they are completely coated. Let the chicken breasts marinade overnight or at least 1 hour.

Remove the chicken from the marinade and grill over high heat for about 9 minutes. Allow the chicken to rest for 5 minutes then cube the chicken.

## Pulled Pork {-}

### Ingredients {-}

* 7.5 lbs pork shoulder

* 2 cups Dr. Pepper

* 2 cans chipotle peppers in adobo sauce

### Instructions {-}

Place pork shoulder in a large crockpot. Cover the pork shoulder in the chipotle peppers (and adobo sauce) and add the Dr. Pepper.

Leave the crockpot on low heat for 8-12 hours.
