language: r
r_version: 3.4
cache: packages
pandoc_version: 1.17
git:
  depth: 3
env:
  global:
  - secure: kKp+BfYapRzNWMsuK1UcaGvrzQPSuWpOZ95bX/tFdAL8zYGXv4P/JL99Bkmr0h6XTYhKGm1Y7GNxD3tsCZdwxNNqnqZgaiKa+K21xA7nHckkKtn/RPFYauxXFu+zwIzWLlLvQRn75O9Ufna6FwmapieAQ4tptomWC7MyRi8f5FDJekrp0SfUPCVXa0TjWIDuo9sF7XovwS/QfnSYafF2tlSydtasp4h0o9u6VkJBzUe2RwJgHNFlU9UFRKn4wfEhGV0Ub35PvXIe01DjlOXt6ohWUTyNlA6SyCv2WbQx55rTHVQlGzVS5c7hrEJnEdeBi15xJsGRAjhNrAh8fLud9vG46nBogfyhK6RcmT7uGlK2eS507dfjkiIDRtYrYOqOEC5ODPsk1DJYHdy1mfczBzy1O0ph5vkGSX0+lPWSeJ2DvHkT8x1+DDN9oTSvwikht7c6Cu2XhbeS8r0mPXoR+JssqFgRZrAP7EY/U2GNRJgxO/ghXCZIfInpNtEeEalfF7PLCob2VDrEbz7lcYy0+Hv2Kx92g5Uk6Qu0ztPcIM11FdOJAVqstWoTad1P56gFIwGsmK9j+Ma0PCOssJuJvwYL9Ai297xUM9qFy+akWlrUVFjEMiCLKIOod4lYBXIQpAOYi+wM8S2+bKKOOolyukfwf8zWaWsvUy+IXkH6PUs=
install:
  - pip install --user awscli
before_script:
- chmod +x ./_build.sh
script:
- "./_build.sh"
deploy:
  provider: s3
  access_key_id: AKIAJMNO772HDA2224HA
  secret_access_key:
    secure: UdVbqXjvaaEApC1DIyhGfRUDxvhlvyLkU5WSuGlDdoJPXTDtWARavyppyydMLzvHpCiaZRj7pKTUZwtzXfwPd0gIaN53Upwukbl1qdjIHg05wk1FFiYxTCPGzhCXS5Z2Rb/kr7/59PdrXT/CWj2LvkqTyU0E8v0259aqQhgMPwTfKvLG9niHIoHQDH1vtwpuQZeS03CQvUaBqb9lcSphQmfre0KWuxwJNH2S+3CGboB0W/aH8GMW3I9OUbXxkieqBbrGyfiLXrIz8cMG6etsuEY72XSam2LoSzo0dqHtlQFHYEDAkcq+FotPFtiYhOWPfjR/FORhRX//GYCuVgoTbt5E5kWKo/2ay2FOTXgF1cCyvpv8Enx2abft9CnunkWbnWzGawAxSzf6a4zO7P/N1g1agXMy8GDkCPS5ZHUoLvFbOkWAeCyirC2cn9BVrIQSVqXUW/uHTXAzdNt0MRdMI14ZKDEl3d9l6+8Eu4vUed8DdXeSh/ZWtqAUA58LZzSDBra8zKYMDsZ9hSh6MSd+xFKUTSE/mfgSwwj7g4nnKb5u1EwXDlOba1u0Eb/OEqlUO69cSOAfegzMlOsdKpOhNyKB85oUr/6FgRa5HPnU8AWSSYCCxN2QwKkdy8NrSWpOZuEf2owPl7AV6IsNqclDvYFzoC1VSUfFD6TZsb6Z28U=
  bucket: cookdown.ellisvalentiner.com
  local-dir: _book
  skip_cleanup: true
  acl: public_read
  on:
    repo: ellisvalentiner/CookDown
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
