language: r
cache: packages
env:
  global:
  - secure: ''
  - secure: kKp+BfYapRzNWMsuK1UcaGvrzQPSuWpOZ95bX/tFdAL8zYGXv4P/JL99Bkmr0h6XTYhKGm1Y7GNxD3tsCZdwxNNqnqZgaiKa+K21xA7nHckkKtn/RPFYauxXFu+zwIzWLlLvQRn75O9Ufna6FwmapieAQ4tptomWC7MyRi8f5FDJekrp0SfUPCVXa0TjWIDuo9sF7XovwS/QfnSYafF2tlSydtasp4h0o9u6VkJBzUe2RwJgHNFlU9UFRKn4wfEhGV0Ub35PvXIe01DjlOXt6ohWUTyNlA6SyCv2WbQx55rTHVQlGzVS5c7hrEJnEdeBi15xJsGRAjhNrAh8fLud9vG46nBogfyhK6RcmT7uGlK2eS507dfjkiIDRtYrYOqOEC5ODPsk1DJYHdy1mfczBzy1O0ph5vkGSX0+lPWSeJ2DvHkT8x1+DDN9oTSvwikht7c6Cu2XhbeS8r0mPXoR+JssqFgRZrAP7EY/U2GNRJgxO/ghXCZIfInpNtEeEalfF7PLCob2VDrEbz7lcYy0+Hv2Kx92g5Uk6Qu0ztPcIM11FdOJAVqstWoTad1P56gFIwGsmK9j+Ma0PCOssJuJvwYL9Ai297xUM9qFy+akWlrUVFjEMiCLKIOod4lYBXIQpAOYi+wM8S2+bKKOOolyukfwf8zWaWsvUy+IXkH6PUs=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
