## Healthy Nachos {-}

### Ingredients {-}

3/4 medium onion chopped

8 oz raw 93% lean ground turkey

1 tsp. Taco Seasoning Blend

¼ cup water(

1 medium orange bell pepper cut into 1-inch wide slices

¼ cup shredded sharp cheddar cheese

1 medium jalapeño seeds and veins removed, sliced (optional)

½ cup pico de gallo or fresh tomato salsa

### Instructions {-}

Preheat oven to 375° F.

Heat medium saucepan, lightly coated with spray, over medium-high heat.

Add onion; cook, stirring frequently, for 4 to 5 minutes, or until onion is translucent.

Add turkey; cook, stirring frequently, for 4 to 5 minutes, or until turkey is no longer pink.

Add Taco Seasoning and water. Mix well; cook, stirring frequently, for 2 minutes, or until water evaporates.

Arrange peppers in an oven-proof baking dish; top with turkey mixture and cheese.

Bake for 5 to 8 minutes, or until cheese melts.

Divide pepper mixture evenly between two serving plates. Top with jalapeños (if desired) and pico de gallo; serve immediately.
